### ISSUE TITLE
Where can I find fireprotDB-pdbID-corrections.csv?

### ISSUE THREAD

**Issue by JinyuanSun** [Kuhlman-Lab/ThermoMPNN#1]
Hello,

I'm currently working on reproducing the training process of the ThermoMPNN project. During the data preprocessing stage, I've come across a requirement for a file named `fireprotDB-pdbID-corrections.csv` (referenced in the code [here](https://github.com/Kuhlman-Lab/ThermoMPNN/blob/d1404a5184219747db56effdc453c5111b89d0ae/preprocessing/1_clean_fireprot_dataset.py#L94)).

However, I haven't been able to locate any guidance on generating this specific file within the repository, nor is the file itself present. I would greatly appreciate it if someone could provide insights into how I can create this file or share it with me if it's available. Your assistance would be invaluable in progressing with my reproduction efforts. Thank you for your time and support.

**Comment by nzrandol** [comment]
Thanks for your interest in ThermoMPNN! I'd recommend looking at our [Zenodo repo](https://zenodo.org/record/8169289) that contains the train/validation/test splits we used for the FireProtDB. Hope that helps!

**Comment by nzrandol** [comment]
Thanks for your interest in ThermoMPNN! I'd recommend looking at our [Zenodo repo](https://zenodo.org/record/8169289) that contains the FireProtDB train/validation/test splits we used. Hope that helps!

**Comment by hdieckhaus** [comment]
Just to add some more context to this: the Zenodo repo includes the preprocessed FireprotDB dataset that was used for all experiments in the ThermoMPNN paper. To run the training or evaluation on the Fireprot dataset referenced in the paper, use the _4_fireprotDB_bestpH.csv_ file from Zenodo.

If you really want to re-run the processing, you can do so starting from the raw FireprotDB dataset (found here [link](https://loschmidt.chemi.muni.cz/fireprotdb/)), then run the _preprocessing scripts_ using the metadata files that we manually compiled. Those files were omitted from the Zenodo repository for clarity, but I will attach them below for you to use if you wish. Hope this helps!

[fireprotDB-curation-metadata.csv](https://github.com/Kuhlman-Lab/ThermoMPNN/files/12455773/fireprotDB-curation-metadata.csv)

[fireprotDB-pdbID-corrections.csv](https://github.com/Kuhlman-Lab/ThermoMPNN/files/12455768/fireprotDB-pdbID-corrections.csv)
