### ISSUE TITLE
Bug in color scale of 3D representations in the Colab implementation

### ISSUE THREAD

**Issue by matiasmachado** [Kuhlman-Lab/ThermoMPNN#12]
Hi!
The Colab implementation of ThermoMPNN is very nice, but I found an issue in the 3D representation (Step 6C).

The color scale for "RAW", "BEST" and "ALA" methods is set from red to blue, but should be the other way around to follow the color code in the matrix image.

if cs = "RdBu", then  "colorDomain" should be set [max_sens, min_sens], to render a scale from blue (stable) to red...

Additionally, the range of the color scale in the 3D representation differs from the matrix image. In particular defining:

min_sens, max_sens = min(sensitivity), max(sensitivity)

May create an asymmetric scale around zero, then a white color may stand for a different value in a linear gradient... A better choice may be using fixed values (e.g. min_sens=-3; max_sens=3) or setting the absolute maximum value to both variables.

Best regards

**Comment by hdieckhaus** [comment]
Hi Matias,

Thank you for bringing this bug to our attention! I agree that it would be good to have the matrix and 3D representation color scales match. I have updated the Colab code as follows:

- color scale for 3D representation now uses ```min_sens, max_sens = -3, 3```
- switched the color scheme from ```RdBu``` to ```BuRd``` to render from blue (stable) to red (unstable)

However, it appears that a recent Colab update may have broken NGLView widgets, which generate the 3D representation. I am unable to get the 3D representation to load now, and have found [some](https://github.com/nglviewer/nglview/issues/1109) [issues](https://github.com/googlecolab/colabtools/issues/4296) that report the same behavior. I have added a note explaining as much in the Colab.

Thanks,
Henry
