### ISSUE TITLE
Hardcoded paths

### ISSUE THREAD

**Issue by amduffy** [Kuhlman-Lab/ThermoMPNN#15]
Hi all,
Thanks for this new package - the paper looks fantastic, and excited to give this a try.

A few hardcoded paths I just wanted to point out/ask for better documentation for that I've come across:

1. Initially when running it after setting up the environment I get the following error:
```
FileNotFoundError: [Errno 2] No such file or directory: '/nas/longleaf/home/dieckhau/ThermoMPNN/ThermoMPNN/vanilla_model_weights/v_48_020.pt'
```
After some digging I found that these are referencing the `local.yaml` file. Would it be possible to add more text to the readme that this file has to be customized during installation, and/or include an installer that will update at least a few based on the repo's location? 

2. `analysis/thermompnn_benchmarking.py` has a hardcoded path on line 220; not sure if it's critical for anything but came across it when looking for 1 above
```
misc_data_loc = '/nas/longleaf/home/dieckhau/protein-stability/enzyme-stability/data'
```

3.  `analysis/custom_inference.py` assumes that the current path is `/path/to/ThermoMPNN/analysis` which prevents calling the python script from another location. Not a huge problem of course and plenty easy enough to work around, but just something I ran into getting this running.

Thank you again!

Edit: Oops - my bad on the local.yaml - sorry about that

**Comment by evancofer** [comment]
Unfortunately, this is still an issue. The README mentions that a `local.yaml` file is needed for some features, but not for `analysis/custom_inference.py`. Actually, this script also crashes due to an absolute path in the `local.yaml` file, which is being used (despite saying the opposite in the README).
