### ISSUE TITLE
mask_attend calculation

### ISSUE THREAD

**Issue by farbod-nobar** [Kuhlman-Lab/ThermoMPNN#18]
Hi, 
In [protein_mpnn_utils.py](https://github.com/Kuhlman-Lab/ThermoMPNN/blob/main/protein_mpnn_utils.py), line 1396, there seems to be a typo (an additional character E in `mask_attendE`):

mask_attend = mask.unsqueeze(-1) * mask_attendE

**Comment by hdieckhaus** [comment]
Hi, thanks for letting us know! Not sure how this got introduced, but we don't ever use that function in ThermoMPNN, so I guess it never triggered an error on our end. In any case, it has been patched and the repo has been updated!
