### ISSUE TITLE
The problem of positive and negative ddG in the Mega scale dataset

### ISSUE THREAD

**Issue by jiaweiguan** [Kuhlman-Lab/ThermoMPNN#2]
![image](https://github.com/Kuhlman-Lab/ThermoMPNN/assets/32994356/6ff87799-313e-4257-ab7f-608fc5bd992b)

Hi, @hdieckhaus 
When I was processing the mega scale dataset, I found that when 'Stabilizing_mut=TRUE', 'ddG_ML' is all positive, is it ddG_ ML=ddG value for mutation (mutant - WT) ? Should I add a minus sign for ‘Stabilizing_ Mut=TRUE data’？

**Comment by hdieckhaus** [comment]
Hi @jiaweiguan, 

The mega scale dataset uses the convention that positive ddG_ML is stabilizing, while negative ddG_ML is destabilizing.
This is used throughout the paper it is from, [Tsuboyama et al. (2023)](https://www.nature.com/articles/s41586-023-06328-6), for example, Extended Data Figure 11.

Unfortunately, different ddG datasets have different conventions - some follow this approach, while others do the opposite. If you want to flip the convention, you need to multiply ALL ddG_ML values by -1, not just where Stabilizing_Mut=True. You can see an example of this in the ThermoMPNN code:
```
# datasets.py, line 161

ddG = -torch.tensor([float(row.ddG_ML)], dtype=torch.float32)
```
Hope this helps!

**Comment by Admire7494** [comment]
Sorry for my late bother.
I wonder when i use custom_inference.py script to pass a custom PDB to ThermoMPNN for site-saturation mutagenesis. The lower ddG_pred in output means the more destability of my protein?
For example, 0.8 means more stable than 0.8 (the ddG_pred)?
