### ISSUE TITLE
Might want to add a section about editing the local.yaml file

### ISSUE THREAD

**Issue by noah-c-noah-do** [Kuhlman-Lab/ThermoMPNN#21]
Thanks for sharing the software, it's very cool! One thing that might help future users is to mention that editing the local.yaml file is necessary before they run. I was very confused by my test run looking for a '/nas/longleaf/home/dieckhau/' folder 😁

**Comment by hdieckhaus** [comment]
Hello, good point! Sorry for any confusion this may have caused. I have added some details on this in the Installation section of the README.
