### ISSUE TITLE
Import Issues caused by sys.path.append()

### ISSUE THREAD

**Issue by asglover** [Kuhlman-Lab/ThermoMPNN#22]
In the import statements in some modules, like SSM.py for example, the following style is used: 

```
import os
import sys
sys.path.append('../') 
from datasets import MegaScaleDataset, ddgBenchDataset, FireProtDataset, Mutation
from protein_mpnn_utils import loss_smoothed, tied_featurize
from train_thermompnn import TransferModelPL
from model_utils import featurize
from thermompnn_benchmarking import compute_centrality, ProteinMPNNBaseline, get_trained_model, ALPHABET
```

A downside to this approach is that if a someone wants to import a function from SSM.py into a module isn't located in the same directory as SSM.py (the most common situation) it will cause a import error because `datasets` and the other modules cannot be found. 

I would propose using the following relative import syntax: 

```
import os
import sys
from ..datasets import MegaScaleDataset, ddgBenchDataset, FireProtDataset, Mutation
from ..protein_mpnn_utils import loss_smoothed, tied_featurize
from ..train_thermompnn import TransferModelPL
from ..model_utils import featurize
from .thermompnn_benchmarking import compute_centrality, ProteinMPNNBaseline, get_trained_model, ALPHABET
```

It is described here: https://docs.python.org/3/reference/import.html#package-relative-imports

I think this is a good change. 
It would improve the usability and readability of the code, and would incur no negative side effects.
I would be happy to create a Pull Request with this fix if you are open to the change. 
Please let me know your thoughts. 

-Austin

**Comment by hdieckhaus** [comment]
Hi Austin,

Sorry for the delayed response. Thanks for this helpful suggestion! I am definitely open to this change. I don't have the time to update the code at the moment, but if you still want to create a Pull Request, I can review and merge it to add this improvement.

Thanks, 
Henry
