### ISSUE TITLE
scoring stability change for higher-order mutants

### ISSUE THREAD

**Issue by adrienchaton** [Kuhlman-Lab/ThermoMPNN#23]
Hi and thanks for sharing this model!

I used the custom_inference.py inference script you provide, it worked fine, outputting ddG predictions for all SPMs.

I am wondering if you have any workflow to expand to higher-order mutants, maybe not exhaustive scanning but e.g. providing a list of N-point mutants and getting scores which account for potential interactions in between combined mutations.

Thanks!

**Comment by hdieckhaus** [comment]
Hi @adrienchaton,

We have just released a new [preprint](https://www.biorxiv.org/content/10.1101/2024.08.20.608844v1) and [repo](https://github.com/Kuhlman-Lab/ThermoMPNN-D) to tackle this very problem! 

To make a long story short, this new model can be used to scan for mutation pairs (N=2), but for higher-order pairs, you are better off using a tool like Rosetta at this time.

**Comment by adrienchaton** [comment]
@hdieckhaus great job! thanks for your follow up and open-sourcing this new model, I will try it soon for sure
