### ISSUE TITLE
Stability score for a sequence

### ISSUE THREAD

**Issue by ahof1704** [Kuhlman-Lab/ThermoMPNN#24]
Hi,

Thank you for sharing this great tool! I was wondering if there is a simple and quick way to use ThermoMPNN to extract a single score that would represent the overall stability of my protein. The heatmap provided as the output is very informative, but at the moment, a score that could indicate how stable the protein is on a scale going from "highly stable" to "not stable at all" would be fantastic. 

Thank you in advance!

**Comment by hdieckhaus** [comment]
Hello,

Unfortunately, ThermoMPNN is trained only on _relative_ stability scores, so it is not really designed to score the wild type protein on an _absolute_ scale. 

To do this kind of holistic evaluation, I would recommend using something with an empirical energy function like [Rosetta](https://docs.rosettacommons.org/demos/latest/tutorials/scoring/scoring) or [FoldX](https://foldxsuite.crg.eu/command/Stability). Hope this helps!
