### ISSUE TITLE
csv file content exmaple for SSM.py

### ISSUE THREAD

**Issue by fayina** [Kuhlman-Lab/ThermoMPNN#25]
I can not find a csv example file for script SSM.py input, Could you please offer me an example?

**Comment by hdieckhaus** [comment]
Hi @fayina,

The SSM.py script is meant for use with a dataset represented by a CSV of mutations and PDB structure. It expects data in the format of the ProtDDG-Bench repository, which you can find [here](https://protddg-bench.github.io). 

Hope this helps!
Henry
