### ISSUE TITLE
Tying Positions For Multichain and Single Chain Inference

### ISSUE THREAD

**Issue by ghost** [Kuhlman-Lab/ThermoMPNN#6]
In proteinMPNN a very powerful feature is the ability to tie arbitrary positions together which allows for the optimization of sequence over repeat proteins and homooligomers. Is this something can be enabled within ThermoMPNN without major modification?

**Comment by hdieckhaus** [comment]
Hello! Sorry for the delayed response. 

ThermoMPNN is currently only configured to predict on monomers and offer a monomer stability ddG for single point mutants. This means that predictions on oligomers are ill-defined, as are multiple mutations carried out on the same monomer. We understand this would be useful features for protein design purposes, and we are working on adding this functionality in the future. 

Thanks,
Henry
