### ISSUE TITLE
Exploring the Detailed Steps of Utilizing a Custom PDB File

### ISSUE THREAD

**Issue by partrita** [Kuhlman-Lab/ThermoMPNN#8]
Could you provide more specific details on how to use a custom PDB file?
Thanks in advance.

**Comment by hdieckhaus** [comment]
Hi Taeyoon,

Sure thing. To use a custom PDB file, you should follow the installation instructions to set up ThermoMPNN, then do as follows:

```
conda activate thermoMPNN
cd analysis/
python custom_inference.py --pdb CUSTOM.pdb --chain A --model_path ../models/thermoMPNN_default.pt 
```

Note: custom.pdb can be substituted with the name of your custom PDB file, and A should be substituted with the specific chain ID that you'd like to use in your PDB. You can leave the chain ID blank if there's only one chain in the structure. To view the details for running the script, you can do ```python custom_inference.py -h``` to see the help messages.

This should output a file called ```ThermoMPNN_inference_CUSTOM.csv``` labeled with the name of your PDB file.

**Comment by partrita** [comment]
> Hi Taeyoon,
> 
> Sure thing. To use a custom PDB file, you should follow the installation instructions to set up ThermoMPNN, then do as follows:
> 
> ```
> conda activate thermoMPNN
> cd analysis/
> python custom_inference.py --pdb CUSTOM.pdb --chain A --model_path ../models/thermoMPNN_default.pt 
> ```
> 
> Note: custom.pdb can be substituted with the name of your custom PDB file, and A should be substituted with the specific chain ID that you'd like to use in your PDB. You can leave the chain ID blank if there's only one chain in the structure. To view the details for running the script, you can do `python custom_inference.py -h` to see the help messages.
> 
> This should output a file called `ThermoMPNN_inference_CUSTOM.csv` labeled with the name of your PDB file.

Thanks @hdieckhaus!
It works works well.
